server:
  port: 8080
  servlet:
    context-path: /identity #dinh vi duoc microservice
    #khi co load balancer apply vao thi no se routing cai request den dung cai micro-service do

spring:
  datasource:
    url : "jdbc:mysql://maglev.proxy.rlwy.net:27052/railway"
    username: root
    password: BsMVkZGVUJzvkcuWKLdKeawRHTBmQAcR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "gbXCYyIhTXm+3ElN/y2aGmqkWuy/u/NPcnYhIjnVQi1UywDKNWNht0Zs2rcYa1HC"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  paths-to-match: /**
